/*
 * SPDX-FileCopyrightText: Copyright 2020-2026 OpenRTX Contributors
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#include "audio_resampler.h"
#include <string.h>

/*
 * Unity-DC-gain Blackman-windowed sinc filters. Coefficients are generated by
 * h[n] = 2*fc/fs*sinc(2*fc/fs*(n-(N-1)/2))*Blackman(n), then divided by sum(h).
 * Baseband: N=81, fs=48000, fc=5800 Hz; preserve 0..3600 Hz, reject >=8000 Hz.
 * Speech: N=97, fs=16000, fc=3500 Hz; preserve 0..3000 Hz, reject >=4000 Hz.
 * These filters convert sample rate; the modem retains its existing RRC filters.
 */
static const float baseband_taps[] = {
    9.5638803384e-20f,  -4.4156798475e-06f, -1.0220790466e-05f,
    7.9885257162e-06f,  6.5759794116e-05f,  1.3190211803e-04f,
    1.2678547031e-04f,  -2.2702917527e-05f, -2.9725674486e-04f,
    -5.3694791547e-04f, -4.9851682787e-04f, -2.3778866291e-05f,
    7.7121268570e-04f,  1.4389036848e-03f,  1.3889019828e-03f,
    2.8599332195e-04f,  -1.5651278629e-03f, -3.1569196221e-03f,
    -3.2240417690e-03f, -1.0677368663e-03f, 2.7055911906e-03f,
    6.1073845618e-03f,  6.6512096389e-03f,  2.9090775915e-03f,
    -4.1250141383e-03f, -1.0876340359e-02f, -1.2734979387e-02f,
    -6.7982456945e-03f, 5.6489994280e-03f,  1.8620197858e-02f,
    2.3783585239e-02f,  1.5018466234e-02f,  -7.0251795461e-03f,
    -3.3076701747e-02f, -4.7814235218e-02f, -3.6371272508e-02f,
    7.9873362503e-03f,  7.8862209557e-02f,  1.5733363366e-01f,
    2.1855307565e-01f,  2.4166284003e-01f,  2.1855307565e-01f,
    1.5733363366e-01f,  7.8862209557e-02f,  7.9873362503e-03f,
    -3.6371272508e-02f, -4.7814235218e-02f, -3.3076701747e-02f,
    -7.0251795461e-03f, 1.5018466234e-02f,  2.3783585239e-02f,
    1.8620197858e-02f,  5.6489994280e-03f,  -6.7982456945e-03f,
    -1.2734979387e-02f, -1.0876340359e-02f, -4.1250141383e-03f,
    2.9090775915e-03f,  6.6512096389e-03f,  6.1073845618e-03f,
    2.7055911906e-03f,  -1.0677368663e-03f, -3.2240417690e-03f,
    -3.1569196221e-03f, -1.5651278629e-03f, 2.8599332195e-04f,
    1.3889019828e-03f,  1.4389036848e-03f,  7.7121268570e-04f,
    -2.3778866291e-05f, -4.9851682787e-04f, -5.3694791547e-04f,
    -2.9725674486e-04f, -2.2702917527e-05f, 1.2678547031e-04f,
    1.3190211803e-04f,  6.5759794116e-05f,  7.9885257162e-06f,
    -1.0220790466e-05f, -4.4156798475e-06f, 9.5638803384e-20f,
};

static const float speech_taps[] = {
    9.0277610304e-35f,  2.5648287056e-06f,  4.1088785004e-06f,
    -2.0689367726e-05f, -3.2325158060e-05f, 4.1139722609e-05f,
    1.0242968547e-04f,  -3.0693080713e-05f, -2.1475891525e-04f,
    -5.5538960032e-05f, 3.4073826856e-04f,  2.6059275424e-04f,
    -4.1543885532e-04f, -6.0408123837e-04f, 3.4004916836e-04f,
    1.0557881752e-03f,  -2.2170937005e-18f, -1.5121785733e-03f,
    -6.9875539533e-04f, 1.7870613986e-03f,  1.7790032619e-03f,
    -1.6279126836e-03f, -3.1383299998e-03f, 7.6502218949e-04f,
    4.5094072832e-03f,  1.0081326448e-03f,  -5.4537212638e-03f,
    -3.7359156749e-03f, 5.4033533107e-03f,  7.2052042595e-03f,
    -3.7543468630e-03f, -1.0879869666e-02f, 1.0744377164e-17f,
    1.3885811459e-02f,  6.1225966723e-03f,  -1.5049943745e-02f,
    -1.4509279164e-02f, 1.2963674647e-02f,  2.4625828707e-02f,
    -5.9777551485e-03f, -3.5531982193e-02f, -8.1362413283e-03f,
    4.5999594577e-02f,  3.3845616800e-02f,  -5.4708208252e-02f,
    -8.6837182420e-02f, 6.0479635887e-02f,  3.1164695759e-01f,
    4.3750167155e-01f,  3.1164695759e-01f,  6.0479635887e-02f,
    -8.6837182420e-02f, -5.4708208252e-02f, 3.3845616800e-02f,
    4.5999594577e-02f,  -8.1362413283e-03f, -3.5531982193e-02f,
    -5.9777551485e-03f, 2.4625828707e-02f,  1.2963674647e-02f,
    -1.4509279164e-02f, -1.5049943745e-02f, 6.1225966723e-03f,
    1.3885811459e-02f,  1.0744377164e-17f,  -1.0879869666e-02f,
    -3.7543468630e-03f, 7.2052042595e-03f,  5.4033533107e-03f,
    -3.7359156749e-03f, -5.4537212638e-03f, 1.0081326448e-03f,
    4.5094072832e-03f,  7.6502218949e-04f,  -3.1383299998e-03f,
    -1.6279126836e-03f, 1.7790032619e-03f,  1.7870613986e-03f,
    -6.9875539533e-04f, -1.5121785733e-03f, -2.2170937005e-18f,
    1.0557881752e-03f,  3.4004916836e-04f,  -6.0408123837e-04f,
    -4.1543885532e-04f, 2.6059275424e-04f,  3.4073826856e-04f,
    -5.5538960032e-05f, -2.1475891525e-04f, -3.0693080713e-05f,
    1.0242968547e-04f,  4.1139722609e-05f,  -3.2325158060e-05f,
    -2.0689367726e-05f, 4.1088785004e-06f,  2.5648287056e-06f,
    9.0277610304e-35f,
};

bool c62_resampler_init(struct c62_resampler *state, uint32_t input_rate,
                        uint32_t output_rate)
{
    memset(state, 0, sizeof(*state));
    if (input_rate != 16000 && output_rate != 16000)
        return false;

    uint32_t other = input_rate == 16000 ? output_rate : input_rate;
    switch (other) {
        case 8000:
            state->taps = speech_taps;
            state->length = sizeof(speech_taps) / sizeof(speech_taps[0]);
            state->up = input_rate == 8000 ? 2 : 1;
            state->down = input_rate == 8000 ? 1 : 2;
            break;
        case 16000:
            state->up = state->down = 1;
            break;
        case 24000:
        case 48000:
            state->taps = baseband_taps;
            state->length = sizeof(baseband_taps) / sizeof(baseband_taps[0]);
            state->up = 48000 / input_rate;
            state->down = 48000 / output_rate;
            break;
        default:
            return false;
    }
    return true;
}

size_t c62_resampler_push(struct c62_resampler *state, int16_t input,
                          int16_t *output)
{
    if (state->length == 0) {
        output[0] = input;
        return 1;
    }

    state->history[state->head] = input;
    size_t count = 0;
    /* Evaluate only output phases, without inserting or multiplying zeros. */
    for (; state->phase < state->up; state->phase += state->down) {
        float sample = 0.0f;
        unsigned int index = state->head;
        for (unsigned int tap = state->phase; tap < state->length;
             tap += state->up) {
            sample += state->taps[tap] * state->history[index];
            index = index == 0 ? C62_RESAMPLER_HISTORY - 1 : index - 1;
        }
        /* Compensate for zero insertion: unity overall amplitude gain. */
        sample *= state->up;
        if (sample > INT16_MAX) {
            sample = INT16_MAX;
            state->clipped++;
        } else if (sample < INT16_MIN) {
            sample = INT16_MIN;
            state->clipped++;
        }
        output[count++] = (int16_t)(sample + (sample >= 0 ? 0.5f : -0.5f));
    }
    state->phase -= state->up;
    state->head = (state->head + 1) % C62_RESAMPLER_HISTORY;
    return count;
}
